name: husky_ci

on:
  push:
    branches: [humble]
    pull_request: [humble]
  schedule:
    - cron: "0 4 * * *" # every day at 4 AM (UTC)

jobs:
  husky_galactic_testing_ci:
    name: Humble Testing
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble, ROS_REPO: testing }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}
  husky_galactic_main_ci:
    name: Humble Main
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble, ROS_REPO: main }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}
